name: Python Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust if you have specific dependencies
    
    - name: Run Python script
      run: python main.py  # Replace `your_script.py` with the path to your Python script
